// js/lang.js
export const translations = {
    tr: {
        game_title: "2D Arcade Futbol",
        start_instruction: "Oynamak için Başla'ya bas!",
        controls_hint: "Kırmızı: WASD | Mavi: OK TUŞLARI",
        team_red: "Kırmızı Takım:",
        team_blue: "Mavi Takım:",
        duration_label: "Süre (Dk):",
        goal_limit_label: "Hedef Skor:",
        game_mode_label: "Oyun Modu:",
        mode_2p: "2 Oyuncu",
        mode_1p: "1 Oyuncu (vs Robo-Messi)",
        ball_choice_label: "Top Seçimi:",
        ball_normal: "Normal ⚽",
        ball_bowling: "Bowling 🎳",
        ball_beach: "Plaj 🏖️",
        ball_pingpong: "Pinpon 🏓",
        sound_effects: "Ses Efektleri 🔊",
        chaos_mode: "🌀 KAOS MODU",
        bomb_mode: "💣 BOMBA MODU",
        sudden_death: "👑 ALTIN GOL",
        start_btn: "MAÇA BAŞLA",
        winner_text: "KAZANAN:",
        draw_text: "BERABERE",
        restart_btn: "TEKRAR OYNA",
        pause_title: "DURAKLATILDI",
        volume_label: "Ses Seviyesi",
        resume_btn: "DEVAM ET",
        main_menu_btn: "ANA MENÜ",
        goal_text: "GOOOL!",
        chaos_title: "🌀 KAOS! 🌀",
        default_red: "Kırmızı",
        default_blue: "Mavi",
        draw: "BERABERE!",
        won: " KAZANDI!",
        chaos_fast_players: "⚡ HIZLANDIK! ⚡",
        chaos_slow_players: "🐌 AĞIR ÇEKİM 🐌",
        chaos_big_ball: "⚽ DEV TOP ⚽",
        chaos_tiny_ball: "📍 MİNİK TOP 📍",
        chaos_big_goals: "🥅 DEV KALELER 🥅",
        chaos_tiny_goals: "🔒 MİNİK KALELER 🔒",
        weather_label: "Hava Durumu:",
        weather_sunny: "Güneşli ☀️",
        weather_rainy: "Yağmurlu 🌧️",
        weather_snowy: "Karlı ❄️",
        weather_icy: "Buzlu 🧊",
        'night_mode': '🌙 GECE MODU (PRO)',
        'replay_toggle': '🎥 REPLAY SİSTEMİ',
        replay_label: "● TEKRAR",
        quick_chat_title: "Hızlı Mesaj (1-4 Tuşları)",
        qc_1: "[1] Harika Pas!",
        qc_2: "[2] İyi Oyundu! (GG)",
        qc_3: "[3] Kusura Bakma!",
        qc_4: "[4] Şanslıydın!",
        auth_title: "⚽ Arcade Futbol",
        auth_subtitle: "Lütfen oynamak için giriş yapın veya kayıt olun.",
        auth_username: "Kullanıcı Adı",
        auth_password: "Şifre",
        auth_login: "GİRİŞ YAP",
        auth_register: "KAYIT OL",
        auth_offline: "ÇEVRİMDIŞI OYNA (KAYITSIZ)",
        logout_btn: "Çıkış Yap",
        coin_text: "Jeton",
        shop_btn: "🛒 MAĞAZA",
        online_title: "🌐 ONLINE 1v1",
        online_connecting: "Bağlanıyor...",
        host_btn: "ODA OLUŞTUR (P1)",
        room_code_text: "Oda Kodun:",
        copy_hint: "(Kopyalamak için tıkla)",
        join_input: "Oda Kodunu Gir (P2)",
        join_btn: "ODAYA KATIL",
        back_btn: "GERİ DÖ",
        lobby_room_name: "Oda",
        lobby_copy_id: "🔗 Link / ID",
        lobby_leave: "🚪 Çık",
        join_red: "Kırmızı Ol",
        join_spec: "İzleyici",
        join_blue: "Mavi Ol",
        lobby_inventory_btn: "🎒 BENİM ENVANTERİM",
        host_only_hint: "Sadece Kurucu değiştirebilir",
        waiting_for_host: "Kurucunun başlatması bekleniyor...",
        stat_title: "İstatistik",
        stat_possession: "Topla Oynama",
        stat_shots: "İsabetli Şut",
        stat_saves: "Kurtarış",
        coins_earned: "Jeton Kazanıldı!",
        continue_btn: "DEVAM ET",
        close_btn: "KAPAT",
        lobbies_title: "🏟️ LOBİLER",
        create_lobby_btn: "✚ Lobi Aç",
        join_with_code: "🔗 Kod ile Katıl",
        code_input_placeholder: "Peer ID veya Lobi Kodu gir...",
        direct_join_btn: "KATIL",
        loading_lobbies: "Lobiler yükleniyor...",
        lobby_create_title: "🏟️ Lobi Oluştur",
        lobby_name_label: "Lobi Adı:",
        lobby_name_placeholder: "Örn: Ramo'nun Maçı",
        lobby_privacy_label: "Gizlilik:",
        privacy_public: "🌐 Herkese Açık",
        privacy_private: "🔒 Gizli",
        create_btn: "OLUŞTUR",
        cancel_btn: "İPTAL",
        inventory_title: "🎒 Envanterim",
        loading_text: "Yükleniyor...",
        connection_timeout: "Bağlantı zaman aşımına uğradı.",
        no_active_lobbies: "Şu an aktif lobi yok. İlk sen aç! 🚀",
        lobbies_failed: "Lobiler yüklenemedi.",
        lobby_not_found: "Lobi bulunamadı veya kapandı."
    },
    en: {
        game_title: "2D Arcade Soccer",
        start_instruction: "Press Start to Play!",
        controls_hint: "Red: WASD | Blue: ARROW KEYS",
        team_red: "Red Team:",
        team_blue: "Blue Team:",
        duration_label: "Duration (Min):",
        goal_limit_label: "Goal Limit:",
        game_mode_label: "Game Mode:",
        mode_2p: "2 Players",
        mode_1p: "1 Player (vs Robo-Messi)",
        ball_choice_label: "Ball Type:",
        ball_normal: "Normal ⚽",
        ball_bowling: "Bowling 🎳",
        ball_beach: "Beach 🏖️",
        ball_pingpong: "Ping Pong 🏓",
        sound_effects: "Sound Effects 🔊",
        chaos_mode: "🌀 CHAOS MODE",
        bomb_mode: "💣 BOMB MODE",
        sudden_death: "👑 GOLDEN GOAL",
        weather_label: "Weather:",
        weather_sunny: "Sunny ☀️",
        weather_rainy: "Rainy 🌧️",
        weather_snowy: "Snowy ❄️",
        weather_icy: "Icy 🧊",
        winner_text: "WINNER:",
        draw_text: "DRAW",
        restart_btn: "PLAY AGAIN",
        pause_title: "PAUSED",
        volume_label: "Volume",
        resume_btn: "RESUME",
        main_menu_btn: "MAIN MENU",
        goal_text: "GOAL!",
        chaos_title: "🌀 CHAOS! 🌀",
        default_red: "Red",
        default_blue: "Blue",
        draw: "DRAW!",
        won: " WON!",
        chaos_fast_players: "⚡ SPEED UP! ⚡",
        chaos_slow_players: "🐌 SLOW MOTION 🐌",
        chaos_big_ball: "⚽ GIANT BALL ⚽",
        chaos_tiny_ball: "📍 TINY BALL 📍",
        chaos_big_goals: "🥅 GIANT GOALS 🥅",
        chaos_tiny_goals: "🔒 TINY GOALS 🔒",
        'night_mode': '🌙 NIGHT MODE (PRO)',
        'replay_toggle': '🎥 REPLAY SYSTEM',
        'start_btn': 'START MATCH',
        replay_label: "● REPLAY",
        quick_chat_title: "Quick Chat (1-4 Keys)",
        qc_1: "[1] Great Pass!",
        qc_2: "[2] Good Game! (GG)",
        qc_3: "[3] My Bad!",
        qc_4: "[4] Lucky!",
        auth_title: "⚽ Arcade Soccer",
        auth_subtitle: "Please login or register to play.",
        auth_username: "Username",
        auth_password: "Password",
        auth_login: "LOGIN",
        auth_register: "REGISTER",
        auth_offline: "PLAY OFFLINE (GUEST)",
        logout_btn: "Logout",
        coin_text: "Coins",
        shop_btn: "🛒 SHOP",
        online_title: "🌐 ONLINE 1v1",
        online_connecting: "Connecting...",
        host_btn: "HOST ROOM (P1)",
        room_code_text: "Room Code:",
        copy_hint: "(Click to copy)",
        join_input: "Enter Room Code (P2)",
        join_btn: "JOIN ROOM",
        back_btn: "GO BACK",
        lobby_room_name: "Room",
        lobby_copy_id: "🔗 Link / ID",
        lobby_leave: "🚪 Leave",
        join_red: "Join Red",
        join_spec: "Spectator",
        join_blue: "Join Blue",
        lobby_inventory_btn: "🎒 MY INVENTORY",
        host_only_hint: "Only Host can change",
        waiting_for_host: "Waiting for host to start...",
        stat_title: "Stat",
        stat_possession: "Possession",
        stat_shots: "Shots on Target",
        stat_saves: "Saves",
        coins_earned: "Coins Earned!",
        continue_btn: "CONTINUE",
        close_btn: "CLOSE",
        lobbies_title: "🏟️ LOBBIES",
        create_lobby_btn: "✚ Create Lobby",
        join_with_code: "🔗 Join with Code",
        code_input_placeholder: "Enter Peer ID or Lobby Code...",
        direct_join_btn: "JOIN",
        loading_lobbies: "Loading lobbies...",
        lobby_create_title: "🏟️ Create Lobby",
        lobby_name_label: "Lobby Name:",
        lobby_name_placeholder: "Ex: Ramo's Match",
        lobby_privacy_label: "Privacy:",
        privacy_public: "🌐 Public",
        privacy_private: "🔒 Private",
        create_btn: "CREATE",
        cancel_btn: "CANCEL",
        inventory_title: "🎒 My Inventory",
        loading_text: "Loading...",
        connection_timeout: "Connection timed out.",
        no_active_lobbies: "No active lobbies. Be the first to host! 🚀",
        lobbies_failed: "Failed to load lobbies.",
        lobby_not_found: "Lobby not found or closed."
    },
    de: {
        game_title: "2D Arcade Fußball",
        start_instruction: "Drücke Start zum Spielen!",
        controls_hint: "Rot: WASD | Blau: PFEILTASTEN",
        team_red: "Team Rot:",
        team_blue: "Team Blau:",
        duration_label: "Dauer (Min):",
        goal_limit_label: "Torlimit:",
        game_mode_label: "Spielmodus:",
        mode_2p: "2 Spieler",
        mode_1p: "1 Spieler (vs Robo-Messi)",
        ball_choice_label: "Ballauswahl:",
        ball_normal: "Normal ⚽",
        ball_bowling: "Bowling 🎳",
        ball_beach: "Strand 🏖️",
        ball_pingpong: "Ping Pong 🏓",
        sound_effects: "Soundeffekte 🔊",
        chaos_mode: "🌀 CHAOS MODUS",
        bomb_mode: "💣 BOMBEN-MODUS",
        sudden_death: "👑 GOLDENES TOR",
        weather_label: "Wetter:",
        weather_sunny: "Sonnig ☀️",
        weather_rainy: "Regnerisch 🌧️",
        weather_snowy: "Schneereich ❄️",
        weather_icy: "Eisig 🧊",
        start_btn: "SPIEL STARTEN",
        winner_text: "GEWINNER:",
        draw_text: "UNENTSCHIEDEN",
        restart_btn: "NEUSTART",
        pause_title: "PAUSE",
        volume_label: "Lautstärke",
        resume_btn: "WEITER",
        main_menu_btn: "HAUPTMENÜ",
        goal_text: "TOR!",
        chaos_title: "🌀 CHAOS! 🌀",
        default_red: "Rot",
        default_blue: "Blau",
        draw: "UNENTSCHIEDEN!",
        won: " HAT GEWONNEN!",
        night_mode: "🌙 NACHTMODUS (PRO)",
        replay_label: "● WIEDERHOLUNG",
        quick_chat_title: "Schnellchat (1-4 Tasten)",
        qc_1: "[1] Guter Pass!",
        qc_2: "[2] Gutes Spiel! (GG)",
        qc_3: "[3] Mein Fehler!",
        qc_4: "[4] Glück gehabt!",
        auth_title: "⚽ Arcade Fußball",
        auth_subtitle: "Zum Spielen bitte anmelden oder registrieren.",
        auth_username: "Benutzername",
        auth_password: "Passwort",
        auth_login: "ANMELDEN",
        auth_register: "REGISTRIEREN",
        auth_offline: "OFFLINE SPIELEN (GAST)",
        logout_btn: "Abmelden",
        coin_text: "Münzen",
        shop_btn: "🛒 SHOP",
        online_title: "🌐 ONLINE 1v1",
        online_connecting: "Verbinden...",
        host_btn: "RAUM ERSTELLEN (P1)",
        room_code_text: "Raumcode:",
        copy_hint: "(Zum Kopieren klicken)",
        join_input: "Raumcode eingeben (P2)",
        join_btn: "RAUM BEITRETEN",
        back_btn: "ZURÜCK",
        lobby_room_name: "Raum",
        lobby_copy_id: "🔗 Link / ID",
        lobby_leave: "🚪 Verlassen",
        join_red: "Rot werden",
        join_spec: "Zuschauer",
        join_blue: "Blau werden",
        lobby_inventory_btn: "🎒 MEIN INVENTAR",
        host_only_hint: "Nur Host kann ändern",
        waiting_for_host: "Warten auf Host...",
        stat_title: "Statistik",
        stat_possession: "Ballbesitz",
        stat_shots: "Torschüsse",
        stat_saves: "Paraden",
        coins_earned: "Münzen Verdient!",
        continue_btn: "WEITER",
        close_btn: "SCHLIESSEN",
        lobbies_title: "🏟️ LOBBYS",
        create_lobby_btn: "✚ Lobby erstellen",
        join_with_code: "🔗 Mit Code beitreten",
        code_input_placeholder: "Peer ID oder Lobby-Code...",
        direct_join_btn: "BEITRETEN",
        loading_lobbies: "Lobbys laden...",
        lobby_create_title: "🏟️ Lobby erstellen",
        lobby_name_label: "Lobby-Name:",
        lobby_name_placeholder: "Bsp: Ramo's Match",
        lobby_privacy_label: "Privatsphäre:",
        privacy_public: "🌐 Öffentlich",
        privacy_private: "🔒 Privat",
        create_btn: "ERSTELLEN",
        cancel_btn: "ABBRECHEN",
        inventory_title: "🎒 Mein Inventar",
        loading_text: "Wird geladen...",
        connection_timeout: "Zeitüberschreitung der Verbindung.",
        no_active_lobbies: "Keine aktiven Lobbys. Sei der Erste! 🚀",
        lobbies_failed: "Lobbys konnten nicht geladen werden.",
        lobby_not_found: "Lobby nicht gefunden oder geschlossen."
    },
    es: {
        game_title: "Fútbol Arcade 2D",
        start_instruction: "¡Presiona Inicio para Jugar!",
        controls_hint: "Rojo: WASD | Azul: FLECHAS",
        team_red: "Equipo Rojo:",
        team_blue: "Equipo Azul:",
        duration_label: "Duración (Min):",
        goal_limit_label: "Límite de Goles:",
        game_mode_label: "Modo de Juego:",
        mode_2p: "2 Jugadores",
        mode_1p: "1 Jugador (vs Robo-Messi)",
        ball_choice_label: "Tipo de Balón:",
        ball_normal: "Normal ⚽",
        ball_bowling: "Bolos 🎳",
        ball_beach: "Playa 🏖️",
        ball_pingpong: "Ping Pong 🏓",
        sound_effects: "Efectos de Sonido 🔊",
        announcer_voice: "Comentarista 🎙️",
        chaos_mode: "🌀 MODO CAOS",
        bomb_mode: "💣 MODO BOMBA",
        sudden_death: "👑 GOL DE ORO",
        weather_label: "Clima:",
        weather_sunny: "Soleado ☀️",
        weather_rainy: "Lluvioso 🌧️",
        weather_snowy: "Nevado ❄️",
        weather_icy: "Helado 🧊",
        start_btn: "INICIAR PARTIDO",
        winner_text: "GANADOR:",
        draw_text: "EMPATE",
        restart_btn: "JUGAR DE NUEVO",
        pause_title: "PAUSADO",
        volume_label: "Volumen",
        resume_btn: "CONTINUAR",
        main_menu_btn: "MENÚ PRINCIPAL",
        goal_text: "¡GOL!",
        chaos_title: "🌀 ¡CAOS! 🌀",
        default_red: "Rojo",
        default_blue: "Azul",
        draw: "¡EMPATE!",
        won: " GANÓ!",
        quick_chat_title: "Chat Rápido (Teclas 1-4)",
        qc_1: "[1] ¡Buen Pase!",
        qc_2: "[2] ¡Buen Juego! (GG)",
        qc_3: "[3] ¡Mi Culpa!",
        qc_4: "[4] ¡Qué Suerte!",
        auth_title: "⚽ Fútbol Arcade",
        auth_subtitle: "Inicia sesión o regístrate para jugar.",
        auth_username: "Usuario",
        auth_password: "Contraseña",
        auth_login: "ENTRAR",
        auth_register: "REGISTRAR",
        auth_offline: "JUGAR OFFLINE (INVITADO)",
        logout_btn: "Salir",
        coin_text: "Monedas",
        shop_btn: "🛒 TIENDA",
        online_title: "🌐 ONLINE 1v1",
        online_connecting: "Conectando...",
        host_btn: "CREAR SALA (P1)",
        room_code_text: "Código Sala:",
        copy_hint: "(Clic para copiar)",
        join_input: "Código de Sala (P2)",
        join_btn: "UNIRSE A SALA",
        back_btn: "VOLVER",
        lobby_room_name: "Sala",
        lobby_copy_id: "🔗 Link / ID",
        lobby_leave: "🚪 Salir",
        join_red: "Unirse a Rojo",
        join_spec: "Espectador",
        join_blue: "Unirse a Azul",
        lobby_inventory_btn: "🎒 MI INVENTARIO",
        host_only_hint: "Solo el creador puede cambiar",
        waiting_for_host: "Esperando al creador...",
        stat_title: "Estadística",
        stat_possession: "Posesión",
        stat_shots: "Tiros a Puerta",
        stat_saves: "Paradas",
        coins_earned: "¡Monedas Ganadas!",
        continue_btn: "CONTINUAR",
        close_btn: "CERRAR",
        lobbies_title: "🏟️ SALAS",
        create_lobby_btn: "✚ Crear Sala",
        join_with_code: "🔗 Unirse con Código",
        code_input_placeholder: "Peer ID o Código...",
        direct_join_btn: "UNIRSE",
        loading_lobbies: "Cargando salas...",
        lobby_create_title: "🏟️ Crear Sala",
        lobby_name_label: "Nombre de Sala:",
        lobby_name_placeholder: "Ej: Partido de Ramo",
        lobby_privacy_label: "Privacidad:",
        privacy_public: "🌐 Pública",
        privacy_private: "🔒 Privada",
        create_btn: "CREAR",
        cancel_btn: "CANCELAR",
        inventory_title: "🎒 Mi Inventario",
        loading_text: "Cargando...",
        connection_timeout: "Tiempo de espera agotado.",
        no_active_lobbies: "No hay salas activas. ¡Sé el primero en crear una! 🚀",
        lobbies_failed: "Error al cargar las salas.",
        lobby_not_found: "Sala no encontrada o cerrada."
    },
    sv: {
        game_title: "2D Arkadfotboll",
        start_instruction: "Tryck på Start för att spela!",
        controls_hint: "Röd: WASD | Blå: PILTANGENTER",
        team_red: "Röda Laget:",
        team_blue: "Blåa Laget:",
        duration_label: "Tid (min):",
        goal_limit_label: "Målgräns:",
        game_mode_label: "Spelläge:",
        mode_2p: "2 Spelare",
        mode_1p: "1 Spelare (mot Robo-Messi)",
        ball_choice_label: "Välj Boll:",
        ball_normal: "Normal ⚽",
        ball_bowling: "Bowling 🎳",
        ball_beach: "Strand 🏖️",
        ball_pingpong: "Pingis 🏓",
        sound_effects: "Ljudeffekter 🔊",
        announcer_voice: "Kommentator 🎙️",
        chaos_mode: "🌀 KAOSLÄGE",
        bomb_mode: "💣 BOMBLÄGE",
        sudden_death: "👑 GOLDEN GOAL",
        weather_label: "Väder:",
        weather_sunny: "Soligt ☀️",
        weather_rainy: "Regnigt 🌧️",
        weather_snowy: "Snöigt ❄️",
        weather_icy: "Isigt 🧊",
        start_btn: "STARTA MATCH",
        winner_text: "VINNARE:",
        draw_text: "OAVGJORT",
        restart_btn: "SPELA IGEN",
        pause_title: "PAUSAD",
        volume_label: "Volym",
        resume_btn: "FORTSÄTT",
        main_menu_btn: "HUVUDMENY",
        goal_text: "MÅÅÅL!",
        chaos_title: "🌀 KAOS! 🌀",
        default_red: "Röd",
        default_blue: "Blå",
        draw: "OAVGJORT!",
        won: " VANN!",
        chaos_fast_players: "⚡ SNABBARE! ⚡",
        chaos_slow_players: "🐌 SLOW MOTION 🐌",
        chaos_big_ball: "⚽ JÄTTEBOLL ⚽",
        chaos_tiny_ball: "📍 MINIBOLL 📍",
        chaos_big_goals: "🥅 JÄTTEMÅL 🥅",
        chaos_tiny_goals: "🔒 MINIMÅL 🔒",
        quick_chat_title: "Snabbchatt (1-4)",
        qc_1: "[1] Bra Passning!",
        qc_2: "[2] Bra Match! (GG)",
        qc_3: "[3] Mitt Fel!",
        qc_4: "[4] Tur!",
        auth_title: "⚽ Arkadfotboll",
        auth_subtitle: "Logga in eller registrera för att spela.",
        auth_username: "Användarnamn",
        auth_password: "Lösenord",
        auth_login: "LOGGA IN",
        auth_register: "REGISTRERA",
        auth_offline: "SPELA OFFLINE (GÄST)",
        logout_btn: "Logga Ut",
        coin_text: "Mynt",
        shop_btn: "🛒 BUTIK",
        online_title: "🌐 ONLINE 1v1",
        online_connecting: "Ansluter...",
        host_btn: "SKAPA RUM (P1)",
        room_code_text: "Rumskod:",
        copy_hint: "(Klicka för kopiera)",
        join_input: "Ange Rumskod (P2)",
        join_btn: "GÅ MED I RUM",
        back_btn: "TILLBAKA",
        lobby_room_name: "Rum",
        lobby_copy_id: "🔗 Länk / ID",
        lobby_leave: "🚪 Lämna",
        join_red: "Bli Röd",
        join_spec: "Åskådare",
        join_blue: "Bli Blå",
        lobby_inventory_btn: "🎒 MIN INVENTARIE",
        host_only_hint: "Endast värden kan ändra",
        waiting_for_host: "Väntar på värden...",
        stat_title: "Statistik",
        stat_possession: "Bollinnehav",
        stat_shots: "Skott på Mål",
        stat_saves: "Räddningar",
        coins_earned: "Intjänade Mynt!",
        continue_btn: "FORTSÄTT",
        close_btn: "STÄNG",
        lobbies_title: "🏟️ LOBBYS",
        create_lobby_btn: "✚ Skapa Lobby",
        join_with_code: "🔗 Gå med Kod",
        code_input_placeholder: "Peer ID eller Rumskod...",
        direct_join_btn: "GÅ MED",
        loading_lobbies: "Laddar lobbys...",
        lobby_create_title: "🏟️ Skapa Lobby",
        lobby_name_label: "Lobbynamn:",
        lobby_name_placeholder: "T.ex: Ramos Match",
        lobby_privacy_label: "Sekretess:",
        privacy_public: "🌐 Offentlig",
        privacy_private: "🔒 Privat",
        create_btn: "SKAPA",
        cancel_btn: "AVBRYT",
        inventory_title: "🎒 Min Inventarie",
        loading_text: "Laddar...",
        connection_timeout: "Anslutning misslyckades. Rummet stängt.",
        no_active_lobbies: "Inga aktiva lobbys. Bli den första! 🚀",
        lobbies_failed: "Det gick inte att ladda lobbys.",
        lobby_not_found: "Lobbyn hittades inte eller är stängd."
    },
    ru: {
        game_title: "2D Аркадный Футбол",
        start_instruction: "Нажми Старт, чтобы играть!",
        controls_hint: "Красные: WASD | Синие: СТРЕЛКИ",
        team_red: "Красная Команда:",
        team_blue: "Синяя Команда:",
        duration_label: "Время (мин):",
        goal_limit_label: "Лимит Голов:",
        game_mode_label: "Режим Игры:",
        mode_2p: "2 Игрока",
        mode_1p: "1 Игрок (против Робо-Месси)",
        ball_choice_label: "Выбор Мяча:",
        ball_normal: "Обычный ⚽",
        ball_bowling: "Боулинг 🎳",
        ball_beach: "Пляжный 🏖️",
        ball_pingpong: "Пинг-понг 🏓",
        sound_effects: "Звуковые Эффекты 🔊",
        announcer_voice: "Комментатор 🎙️",
        chaos_mode: "🌀 РЕЖИМ ХАОСА",
        bomb_mode: "💣 РЕЖИМ БОМБЫ",
        sudden_death: "👑 ЗОЛОТОЙ ГОЛ",
        weather_label: "Погода:",
        weather_sunny: "Солнечно ☀️",
        weather_rainy: "Дождливо 🌧️",
        weather_snowy: "Снежно ❄️",
        weather_icy: "Лед 🧊",
        start_btn: "НАЧАТЬ МАТЧ",
        winner_text: "ПОБЕДИТЕЛЬ:",
        draw_text: "НИЧЬЯ",
        restart_btn: "ИГРАТЬ СНОВА",
        pause_title: "ПАУЗА",
        volume_label: "Громкость",
        resume_btn: "ПРОДОЛЖИТЬ",
        main_menu_btn: "ГЛАВНОЕ МЕНЮ",
        goal_text: "ГОООЛ!",
        chaos_title: "🌀 ХАОС! 🌀",
        default_red: "Красные",
        default_blue: "Синие",
        draw: "НИЧЬЯ!",
        won: " ПОБЕДИЛ!",
        chaos_fast_players: "⚡ УСКОРЕНИЕ! ⚡",
        chaos_slow_players: "🐌 ЗАМЕДЛЕНИЕ 🐌",
        chaos_big_ball: "⚽ ГИГАНТСКИЙ МЯЧ ⚽",
        chaos_tiny_ball: "📍 МИНИ МЯЧ 📍",
        chaos_big_goals: "🥅 ГИГАНТСКИЕ ВОРОТА 🥅",
        chaos_tiny_goals: "🔒 МИНИ ВОРОТА 🔒",
        quick_chat_title: "Быстрый Чат (Кнопки 1-4)",
        qc_1: "[1] Отличный пас!",
        qc_2: "[2] Хорошая игра! (GG)",
        qc_3: "[3] Моя вина!",
        qc_4: "[4] Повезло!",
        auth_title: "⚽ Аркадный Футбол",
        auth_subtitle: "Войдите или зарегистрируйтесь.",
        auth_username: "Имя Пользователя",
        auth_password: "Пароль",
        auth_login: "ВОЙТИ",
        auth_register: "РЕГИСТРАЦИЯ",
        auth_offline: "ИГРАТЬ ОФФЛАЙН (ГОСТЬ)",
        logout_btn: "Выйти",
        coin_text: "Монеты",
        shop_btn: "🛒 МАГАЗИН",
        online_title: "🌐 ОНЛАЙН 1v1",
        online_connecting: "Подключение...",
        host_btn: "СОЗДАТЬ КОМНАТУ (P1)",
        room_code_text: "Код Комнаты:",
        copy_hint: "(Копировать)",
        join_input: "Введите Код (P2)",
        join_btn: "ПРИСОЕДИНИТЬСЯ",
        back_btn: "НАЗАД",
        lobby_room_name: "Комната",
        lobby_copy_id: "🔗 Код / ID",
        lobby_leave: "🚪 Выйти",
        join_red: "За Красных",
        join_spec: "Зритель",
        join_blue: "За Синих",
        lobby_inventory_btn: "🎒 МОЙ ИНВЕНТАРЬ",
        host_only_hint: "Может менять только Хост",
        waiting_for_host: "Ожидание хоста...",
        stat_title: "Статистика",
        stat_possession: "Владение",
        stat_shots: "Удары в створ",
        stat_saves: "Сейвы",
        coins_earned: "Заработано Монет!",
        continue_btn: "ПРОДОЛЖИТЬ",
        close_btn: "ЗАКРЫТЬ",
        lobbies_title: "🏟️ ЛОББИ",
        create_lobby_btn: "✚ Создать Лобби",
        join_with_code: "🔗 Войти по Коду",
        code_input_placeholder: "Peer ID или Код...",
        direct_join_btn: "ВОЙТИ",
        loading_lobbies: "Загрузка лобби...",
        lobby_create_title: "🏟️ Создать Лобби",
        lobby_name_label: "Имя Лобби:",
        lobby_name_placeholder: "Прим: Матч Рамо",
        lobby_privacy_label: "Приватность:",
        privacy_public: "🌐 Открыто",
        privacy_private: "🔒 Закрыто",
        create_btn: "СОЗДАТЬ",
        cancel_btn: "ОТМЕНА",
        inventory_title: "🎒 Мой Инвентарь",
        loading_text: "Загрузка...",
        connection_timeout: "Тайм-аут. Комната закрыта.",
        no_active_lobbies: "Нет активных лобби. Создай первым! 🚀",
        lobbies_failed: "Не удалось загрузить лобби.",
        lobby_not_found: "Лобби не найдено или закрыто."
    }
};

export let currentLang = localStorage.getItem('lang') || 'tr';

export function t(key) {
    if (translations[currentLang] && translations[currentLang][key]) {
        return translations[currentLang][key];
    }
    return key;
}

export function updateLanguage(lang) {
    if (!translations[lang]) return;
    currentLang = lang;
    localStorage.setItem('lang', lang);

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) {
            el.innerText = translations[lang][key];
        }
    });

    const weatherLabel = document.querySelector('label[data-i18n="weather_label"]');
    if (weatherLabel) {
        weatherLabel.innerText = translations[lang]['weather_label'];
    }

    const p1 = document.getElementById('p1NameInput');
    const p2 = document.getElementById('p2NameInput');

    const matchesDefault = (val, key) => {
        return Object.values(translations).some(t => t[key] === val);
    };

    if (p1 && matchesDefault(p1.value, 'default_red')) {
        p1.value = translations[lang]['default_red'];
    }
    if (p2 && matchesDefault(p2.value, 'default_blue')) {
        p2.value = translations[lang]['default_blue'];
    }

    // Special placeholders and innerHTML that data-i18n might miss
    const directJoinInput = document.getElementById('directJoinInput');
    if (directJoinInput) directJoinInput.placeholder = t('code_input_placeholder');

    const authUsername = document.getElementById('authUsername');
    if (authUsername) authUsername.placeholder = t('auth_username');

    const authPassword = document.getElementById('authPassword');
    if (authPassword) authPassword.placeholder = t('auth_password');

    const lobbyNameInput = document.getElementById('lobbyNameInput');
    if (lobbyNameInput) lobbyNameInput.placeholder = t('lobby_name_placeholder');

    const joinIdInput = document.getElementById('joinIdInput');
    if (joinIdInput) joinIdInput.placeholder = t('join_input');

    window.dispatchEvent(new Event('langChanged'));
}

document.addEventListener('DOMContentLoaded', () => {
    const langSelect = document.getElementById('languageSelect');
    if (langSelect) {
        langSelect.value = currentLang;
        langSelect.addEventListener('change', (e) => {
            updateLanguage(e.target.value);
        });
    }
    updateLanguage(currentLang);
});
